name: make

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: festvox/speech_tools
        path: speech_tools
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: festival
    - run: |
       cd speech_tools
       ./configure
       make
       make test
    - run: |
       cd festival
       ./configure
       make
